# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Project in Mathematical Modeling (CB1020)
author: Patrick Norman, Josefine H. Andersen and Marco Bauer
logo: logo.png
copyright              : "2025"  # Copyright year to be placed in the footer
exclude_patterns       : [ README.md, data_input, cb1020.yml, docs/ode.ipynb]
only_build_toc_files   : false

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/kthpanor/cb1020
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button     : true
  use_repository_button : true
  binderhub_url         : false
  favicon               : favicon.png

